/* Generated By:JJTree: Do not edit this line. ASTExcerptFunction.java */

package org.apache.jackrabbit.spi.commons.query.sql;

public class ASTExcerptFunction extends SimpleNode {
  public ASTExcerptFunction(int id) {
    super(id);
  }

  public ASTExcerptFunction(JCRSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JCRSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
