/* Generated By:JJTree: Do not edit this line. ASTOrderByClause.java */

package org.apache.jackrabbit.spi.commons.query.sql;

public class ASTOrderByClause extends SimpleNode {
  public ASTOrderByClause(int id) {
    super(id);
  }

  public ASTOrderByClause(JCRSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JCRSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
