/* Generated By:JJTree: Do not edit this line. ASTOrderSpec.java */

package org.apache.jackrabbit.spi.commons.query.sql;

public class ASTOrderSpec extends SimpleNode {
  public ASTOrderSpec(int id) {
    super(id);
  }

  public ASTOrderSpec(JCRSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JCRSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
