/* Generated By:JJTree: Do not edit this line. /home/jukka/src/jackrabbit/jackrabbit-spi-commons/target/generated-sources/jjtree/org/apache/jackrabbit/spi/commons/query/sql/JCRSQLParserTreeConstants.java */

package org.apache.jackrabbit.spi.commons.query.sql;

public interface JCRSQLParserTreeConstants
{
  public int JJTQUERY = 0;
  public int JJTSELECTLIST = 1;
  public int JJTVOID = 2;
  public int JJTFROMCLAUSE = 3;
  public int JJTWHERECLAUSE = 4;
  public int JJTPREDICATE = 5;
  public int JJTLOWERFUNCTION = 6;
  public int JJTUPPERFUNCTION = 7;
  public int JJTOREXPRESSION = 8;
  public int JJTANDEXPRESSION = 9;
  public int JJTNOTEXPRESSION = 10;
  public int JJTBRACKETEXPRESSION = 11;
  public int JJTCONTAINSEXPRESSION = 12;
  public int JJTLITERAL = 13;
  public int JJTIDENTIFIER = 14;
  public int JJTEXCERPTFUNCTION = 15;
  public int JJTORDERBYCLAUSE = 16;
  public int JJTORDERSPEC = 17;
  public int JJTASCENDINGORDERSPEC = 18;
  public int JJTDESCENDINGORDERSPEC = 19;


  public String[] jjtNodeName = {
    "Query",
    "SelectList",
    "void",
    "FromClause",
    "WhereClause",
    "Predicate",
    "LowerFunction",
    "UpperFunction",
    "OrExpression",
    "AndExpression",
    "NotExpression",
    "BracketExpression",
    "ContainsExpression",
    "Literal",
    "Identifier",
    "ExcerptFunction",
    "OrderByClause",
    "OrderSpec",
    "AscendingOrderSpec",
    "DescendingOrderSpec",
  };
}
