/* Generated By:JJTree: Do not edit this line. ASTSelectList.java */

package org.apache.jackrabbit.spi.commons.query.sql;

public class ASTSelectList extends SimpleNode {
  public ASTSelectList(int id) {
    super(id);
  }

  public ASTSelectList(JCRSQLParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JCRSQLParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
