/* Generated By:JJTree&JavaCC: Do not edit this line. XPathConstants.java */
package org.apache.jackrabbit.spi.commons.query.xpath;

public interface XPathConstants {

  int EOF = 0;
  int IntegerLiteral = 1;
  int DecimalLiteral = 2;
  int DoubleLiteral = 3;
  int StringLiteral = 4;
  int StringLiteralForKindTest = 5;
  int XQueryVersion = 6;
  int StringLiteralForVersion = 7;
  int XQueryEncoding = 8;
  int AtStringLiteral = 9;
  int URLLiteral = 10;
  int ModuleNamespace = 11;
  int skip_ = 13;
  int NotOccurrenceIndicator = 14;
  int ProcessingInstructionStart = 15;
  int ProcessingInstructionStartForElementContent = 16;
  int ProcessingInstructionEnd = 17;
  int AxisChild = 18;
  int AxisDescendant = 19;
  int AxisParent = 20;
  int AxisAttribute = 21;
  int AxisSelf = 22;
  int AxisDescendantOrSelf = 23;
  int AxisAncestor = 24;
  int AxisFollowingSibling = 25;
  int AxisPrecedingSibling = 26;
  int AxisFollowing = 27;
  int AxisPreceding = 28;
  int AxisAncestorOrSelf = 29;
  int DefineFunction = 30;
  int DeclareOrdering = 31;
  int Ordered = 32;
  int Unordered = 33;
  int DeclareDefaultOrderingEmpty = 34;
  int DeclareInheritNamespaces = 35;
  int Yes = 36;
  int No = 37;
  int External = 38;
  int Or = 39;
  int And = 40;
  int Div = 41;
  int Idiv = 42;
  int Mod = 43;
  int Multiply = 44;
  int In = 45;
  int PITarget = 46;
  int Prefix = 47;
  int LocalPart = 48;
  int VariableIndicator = 49;
  int VarName = 50;
  int ValidationMode = 51;
  int SchemaModeForDeclareConstruction = 52;
  int Nillable = 53;
  int DeclareConstruction = 54;
  int Satisfies = 55;
  int Return = 56;
  int Then = 57;
  int Else = 58;
  int Default = 59;
  int DeclareXMLSpace = 60;
  int DeclareBaseURI = 61;
  int XMLSpacePreserve = 62;
  int XMLSpaceStrip = 63;
  int Namespace = 64;
  int DeclareNamespace = 65;
  int To = 66;
  int Where = 67;
  int Collation = 68;
  int Intersect = 69;
  int Union = 70;
  int Except = 71;
  int As = 72;
  int AtWord = 73;
  int Case = 74;
  int Instanceof = 75;
  int Castable = 76;
  int Item = 77;
  int ElementType = 78;
  int AttributeType = 79;
  int SchemaElementType = 80;
  int SchemaAttributeType = 81;
  int OrderedOpen = 82;
  int UnorderedOpen = 83;
  int ElementQNameLbrace = 84;
  int AttributeQNameLbrace = 85;
  int PINCNameLbrace = 86;
  int PILbrace = 87;
  int CommentLbrace = 88;
  int ElementLbrace = 89;
  int AttributeLbrace = 90;
  int TextLbrace = 91;
  int DeclareCollation = 92;
  int DefaultElement = 93;
  int DeclareDefaultElement = 94;
  int DeclareDefaultFunction = 95;
  int EmptyTok = 96;
  int ImportSchemaToken = 97;
  int ImportModuleToken = 98;
  int Nmstart = 99;
  int Nmchar = 100;
  int Star = 101;
  int AnyName = 102;
  int NCNameColonStar = 103;
  int StarColonNCName = 104;
  int Root = 105;
  int RootDescendants = 106;
  int Slash = 107;
  int SlashSlash = 108;
  int Equals = 109;
  int AssignEquals = 110;
  int Is = 111;
  int NotEquals = 112;
  int LtEquals = 113;
  int LtLt = 114;
  int GtEquals = 115;
  int GtGt = 116;
  int FortranEq = 117;
  int FortranNe = 118;
  int FortranGt = 119;
  int FortranGe = 120;
  int FortranLt = 121;
  int FortranLe = 122;
  int ColonEquals = 123;
  int Lt = 124;
  int Gt = 125;
  int Minus = 126;
  int Plus = 127;
  int UnaryMinus = 128;
  int UnaryPlus = 129;
  int OccurrenceZeroOrOne = 130;
  int OccurrenceZeroOrMore = 131;
  int OccurrenceOneOrMore = 132;
  int Vbar = 133;
  int Lpar = 134;
  int At = 135;
  int Lbrack = 136;
  int Rbrack = 137;
  int Rpar = 138;
  int RparForKindTest = 139;
  int Some = 140;
  int Every = 141;
  int ForVariable = 142;
  int LetVariable = 143;
  int CastAs = 144;
  int TreatAs = 145;
  int ValidateLbrace = 146;
  int ValidateSchemaMode = 147;
  int Digits = 148;
  int DocumentLpar = 149;
  int DocumentLparForKindTest = 150;
  int DocumentLbrace = 151;
  int NodeLpar = 152;
  int CommentLpar = 153;
  int TextLpar = 154;
  int ProcessingInstructionLpar = 155;
  int ElementTypeForKindTest = 156;
  int ElementTypeForDocumentTest = 157;
  int AttributeTypeForKindTest = 158;
  int SchemaElementTypeForKindTest = 159;
  int SchemaElementTypeForDocumentTest = 160;
  int SchemaAttributeTypeForKindTest = 161;
  int ProcessingInstructionLparForKindTest = 162;
  int TextLparForKindTest = 163;
  int CommentLparForKindTest = 164;
  int NodeLparForKindTest = 165;
  int IfLpar = 166;
  int TypeswitchLpar = 167;
  int Comma = 168;
  int CommaForKindTest = 169;
  int SemiColon = 170;
  int QuerySeparator = 171;
  int OpenQuot = 172;
  int CloseQuot = 173;
  int Dot = 174;
  int DotDot = 175;
  int OrderBy = 176;
  int OrderByStable = 177;
  int Ascending = 178;
  int Descending = 179;
  int EmptyGreatest = 180;
  int EmptyLeast = 181;
  int DefineVariable = 182;
  int QNameForSequenceType = 183;
  int QNameForAtomicType = 184;
  int QNameForItemType = 185;
  int ExtensionQName = 186;
  int QNameLpar = 187;
  int NCNameForPrefix = 188;
  int NCNameForPI = 189;
  int CdataSectionStart = 190;
  int CdataSectionStartForElementContent = 191;
  int CdataSectionEnd = 192;
  int PredefinedEntityRef = 193;
  int CharRef = 194;
  int HexDigits = 195;
  int StartTagOpen = 196;
  int StartTagOpenRoot = 197;
  int StartTagClose = 198;
  int EmptyTagClose = 199;
  int EndTagOpen = 200;
  int EndTagClose = 201;
  int ValueIndicator = 202;
  int TagQName = 203;
  int Lbrace = 204;
  int LbraceExprEnclosure = 205;
  int LCurlyBraceEscape = 206;
  int RCurlyBraceEscape = 207;
  int EscapeQuot = 208;
  int EscapeApos = 209;
  int ElementContentChar = 210;
  int QuotAttrContentChar = 211;
  int AposAttrContentChar = 212;
  int CommentContentChar = 213;
  int CommentContentCharDash = 214;
  int PIContentChar = 215;
  int CDataSectionChar = 216;
  int OpenApos = 217;
  int CloseApos = 218;
  int Pragma = 219;
  int MUExtension = 220;
  int ExtensionContents = 221;
  int ExtensionStart = 222;
  int ExtensionContentChar = 223;
  int ExtensionEnd = 224;
  int Comment = 225;
  int CommentContents = 226;
  int CommentStart = 227;
  int CommentContent = 228;
  int CommentEnd = 229;
  int PragmaKeyword = 230;
  int Extension = 231;
  int XmlCommentStart = 232;
  int XmlCommentStartForElementContent = 233;
  int XmlCommentEnd = 234;
  int QName = 235;
  int NCName = 236;
  int S = 237;
  int SForPI = 238;
  int SForExt = 239;
  int Char = 240;
  int Rbrace = 241;
  int WhitespaceChar = 242;
  int Letter = 243;
  int BaseChar = 244;
  int Ideographic = 245;
  int CombiningChar = 246;
  int Digit = 247;
  int Extender = 248;
  int NotOperatorKeyword = 249;
  int NotNumber = 250;

  int DEFAULT = 0;
  int OPERATOR = 1;
  int KINDTESTFORPI = 2;
  int XQUERYVERSION = 3;
  int ITEMTYPE = 4;
  int NAMESPACEDECL = 5;
  int NAMESPACEKEYWORD = 6;
  int KINDTEST = 7;
  int XMLSPACE_DECL = 8;
  int SINGLETYPE = 9;
  int VARNAME = 10;
  int OCCURRENCEINDICATOR = 11;
  int CLOSEKINDTEST = 12;
  int ELEMENT_CONTENT = 13;
  int PROCESSING_INSTRUCTION = 14;
  int PROCESSING_INSTRUCTION_CONTENT = 15;
  int START_TAG = 16;
  int QUOT_ATTRIBUTE_CONTENT = 17;
  int EXT_NAME = 18;
  int CDATA_SECTION = 19;
  int APOS_ATTRIBUTE_CONTENT = 20;
  int END_TAG = 21;
  int XML_COMMENT = 22;
  int EXPR_COMMENT = 23;
  int EXT_CONTENT = 24;
  int EXT_KEY = 25;

  String[] tokenImage = {
    "<EOF>",
    "<IntegerLiteral>",
    "<DecimalLiteral>",
    "<DoubleLiteral>",
    "<StringLiteral>",
    "<StringLiteralForKindTest>",
    "<XQueryVersion>",
    "<StringLiteralForVersion>",
    "\"encoding\"",
    "<AtStringLiteral>",
    "<URLLiteral>",
    "<ModuleNamespace>",
    "<token of kind 12>",
    "<skip_>",
    "<NotOccurrenceIndicator>",
    "\"<?\"",
    "\"<?\"",
    "\"?>\"",
    "<AxisChild>",
    "<AxisDescendant>",
    "<AxisParent>",
    "<AxisAttribute>",
    "<AxisSelf>",
    "<AxisDescendantOrSelf>",
    "<AxisAncestor>",
    "<AxisFollowingSibling>",
    "<AxisPrecedingSibling>",
    "<AxisFollowing>",
    "<AxisPreceding>",
    "<AxisAncestorOrSelf>",
    "<DefineFunction>",
    "<DeclareOrdering>",
    "\"ordered\"",
    "\"unordered\"",
    "<DeclareDefaultOrderingEmpty>",
    "<DeclareInheritNamespaces>",
    "\"yes\"",
    "\"no\"",
    "\"external\"",
    "\"or\"",
    "\"and\"",
    "\"div\"",
    "\"idiv\"",
    "\"mod\"",
    "\"*\"",
    "\"in\"",
    "<PITarget>",
    "<Prefix>",
    "<LocalPart>",
    "\"$\"",
    "<VarName>",
    "<ValidationMode>",
    "<SchemaModeForDeclareConstruction>",
    "\"?\"",
    "<DeclareConstruction>",
    "\"satisfies\"",
    "\"return\"",
    "\"then\"",
    "\"else\"",
    "\"default\"",
    "<DeclareXMLSpace>",
    "<DeclareBaseURI>",
    "\"preserve\"",
    "\"strip\"",
    "\"namespace\"",
    "<DeclareNamespace>",
    "\"to\"",
    "\"where\"",
    "\"collation\"",
    "\"intersect\"",
    "\"union\"",
    "\"except\"",
    "\"as\"",
    "\"at\"",
    "\"case\"",
    "<Instanceof>",
    "<Castable>",
    "<Item>",
    "<ElementType>",
    "<AttributeType>",
    "<SchemaElementType>",
    "<SchemaAttributeType>",
    "<OrderedOpen>",
    "<UnorderedOpen>",
    "<ElementQNameLbrace>",
    "<AttributeQNameLbrace>",
    "<PINCNameLbrace>",
    "<PILbrace>",
    "<CommentLbrace>",
    "<ElementLbrace>",
    "<AttributeLbrace>",
    "<TextLbrace>",
    "<DeclareCollation>",
    "<DefaultElement>",
    "<DeclareDefaultElement>",
    "<DeclareDefaultFunction>",
    "<EmptyTok>",
    "<ImportSchemaToken>",
    "<ImportModuleToken>",
    "<Nmstart>",
    "<Nmchar>",
    "\"*\"",
    "\"*\"",
    "<NCNameColonStar>",
    "<StarColonNCName>",
    "\"/\"",
    "\"//\"",
    "\"/\"",
    "\"//\"",
    "\"=\"",
    "\"=\"",
    "\"is\"",
    "\"!=\"",
    "\"<=\"",
    "\"<<\"",
    "\">=\"",
    "\">>\"",
    "\"eq\"",
    "\"ne\"",
    "\"gt\"",
    "\"ge\"",
    "\"lt\"",
    "\"le\"",
    "\":=\"",
    "\"<\"",
    "\">\"",
    "\"-\"",
    "\"+\"",
    "\"-\"",
    "\"+\"",
    "\"?\"",
    "\"*\"",
    "\"+\"",
    "\"|\"",
    "\"(\"",
    "\"@\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\")\"",
    "<Some>",
    "<Every>",
    "<ForVariable>",
    "<LetVariable>",
    "<CastAs>",
    "<TreatAs>",
    "<ValidateLbrace>",
    "<ValidateSchemaMode>",
    "<Digits>",
    "<DocumentLpar>",
    "<DocumentLparForKindTest>",
    "<DocumentLbrace>",
    "<NodeLpar>",
    "<CommentLpar>",
    "<TextLpar>",
    "<ProcessingInstructionLpar>",
    "<ElementTypeForKindTest>",
    "<ElementTypeForDocumentTest>",
    "<AttributeTypeForKindTest>",
    "<SchemaElementTypeForKindTest>",
    "<SchemaElementTypeForDocumentTest>",
    "<SchemaAttributeTypeForKindTest>",
    "<ProcessingInstructionLparForKindTest>",
    "<TextLparForKindTest>",
    "<CommentLparForKindTest>",
    "<NodeLparForKindTest>",
    "<IfLpar>",
    "<TypeswitchLpar>",
    "\",\"",
    "\",\"",
    "\";\"",
    "\"%%%\"",
    "\"\\\"\"",
    "\"\\\"\"",
    "\".\"",
    "\"..\"",
    "<OrderBy>",
    "<OrderByStable>",
    "\"ascending\"",
    "\"descending\"",
    "<EmptyGreatest>",
    "<EmptyLeast>",
    "<DefineVariable>",
    "<QNameForSequenceType>",
    "<QNameForAtomicType>",
    "<QNameForItemType>",
    "<ExtensionQName>",
    "<QNameLpar>",
    "<NCNameForPrefix>",
    "<NCNameForPI>",
    "\"<![CDATA[\"",
    "\"<![CDATA[\"",
    "<CdataSectionEnd>",
    "<PredefinedEntityRef>",
    "<CharRef>",
    "<HexDigits>",
    "\"<\"",
    "\"<\"",
    "\">\"",
    "\"/>\"",
    "\"</\"",
    "\">\"",
    "\"=\"",
    "<TagQName>",
    "\"{\"",
    "\"{\"",
    "\"{{\"",
    "\"}}\"",
    "\"\\\"\\\"\"",
    "\"\\\'\\\'\"",
    "<ElementContentChar>",
    "<QuotAttrContentChar>",
    "<AposAttrContentChar>",
    "<CommentContentChar>",
    "<CommentContentCharDash>",
    "<PIContentChar>",
    "<CDataSectionChar>",
    "\"\\\'\"",
    "\"\\\'\"",
    "<Pragma>",
    "<MUExtension>",
    "<ExtensionContents>",
    "\"(::\"",
    "<ExtensionContentChar>",
    "\"::)\"",
    "<Comment>",
    "<CommentContents>",
    "\"(:\"",
    "<CommentContent>",
    "\":)\"",
    "\"pragma\"",
    "\"extension\"",
    "\"<!--\"",
    "\"<!--\"",
    "\"-->\"",
    "<QName>",
    "<NCName>",
    "<S>",
    "<SForPI>",
    "<SForExt>",
    "<Char>",
    "\"}\"",
    "<WhitespaceChar>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<Digit>",
    "<Extender>",
    "<NotOperatorKeyword>",
    "<NotNumber>",
  };

}
