/* Generated By:JJTree: Do not edit this line. /home/jukka/src/jackrabbit/jackrabbit-spi-commons/target/generated-sources/jjtree/org/apache/jackrabbit/spi/commons/query/xpath/XPathTreeConstants.java */

package org.apache.jackrabbit.spi.commons.query.xpath;

public interface XPathTreeConstants
{
  public int JJTXPATH2 = 0;
  public int JJTQUERYLIST = 1;
  public int JJTMODULE = 2;
  public int JJTVERSIONDECL = 3;
  public int JJTXQUERYVERSION = 4;
  public int JJTSTRINGLITERALFORVERSION = 5;
  public int JJTXQUERYENCODING = 6;
  public int JJTMAINMODULE = 7;
  public int JJTLIBRARYMODULE = 8;
  public int JJTMODULEDECL = 9;
  public int JJTMODULENAMESPACE = 10;
  public int JJTNCNAMEFORPREFIX = 11;
  public int JJTASSIGNEQUALS = 12;
  public int JJTURLLITERAL = 13;
  public int JJTPROLOG = 14;
  public int JJTSETTER = 15;
  public int JJTIMPORT = 16;
  public int JJTSEPARATOR = 17;
  public int JJTNAMESPACEDECL = 18;
  public int JJTDECLARENAMESPACE = 19;
  public int JJTXMLSPACEDECL = 20;
  public int JJTDECLAREXMLSPACE = 21;
  public int JJTXMLSPACEPRESERVE = 22;
  public int JJTXMLSPACESTRIP = 23;
  public int JJTDEFAULTNAMESPACEDECL = 24;
  public int JJTDECLAREDEFAULTELEMENT = 25;
  public int JJTDECLAREDEFAULTFUNCTION = 26;
  public int JJTNAMESPACE = 27;
  public int JJTORDERINGMODEDECL = 28;
  public int JJTDECLAREORDERING = 29;
  public int JJTORDERED = 30;
  public int JJTUNORDERED = 31;
  public int JJTEMPTYORDERINGDECL = 32;
  public int JJTDECLAREDEFAULTORDERINGEMPTY = 33;
  public int JJTEMPTYGREATEST = 34;
  public int JJTEMPTYLEAST = 35;
  public int JJTINHERITNAMESPACESDECL = 36;
  public int JJTDECLAREINHERITNAMESPACES = 37;
  public int JJTYES = 38;
  public int JJTNO = 39;
  public int JJTDEFAULTCOLLATIONDECL = 40;
  public int JJTDECLARECOLLATION = 41;
  public int JJTBASEURIDECL = 42;
  public int JJTDECLAREBASEURI = 43;
  public int JJTSCHEMAIMPORT = 44;
  public int JJTIMPORTSCHEMATOKEN = 45;
  public int JJTATSTRINGLITERAL = 46;
  public int JJTSTRINGLITERAL = 47;
  public int JJTSCHEMAPREFIX = 48;
  public int JJTDEFAULTELEMENT = 49;
  public int JJTMODULEIMPORT = 50;
  public int JJTIMPORTMODULETOKEN = 51;
  public int JJTVARDECL = 52;
  public int JJTDEFINEVARIABLE = 53;
  public int JJTVARNAME = 54;
  public int JJTCOLONEQUALS = 55;
  public int JJTEXTERNAL = 56;
  public int JJTCONSTRUCTIONDECL = 57;
  public int JJTDECLARECONSTRUCTION = 58;
  public int JJTSCHEMAMODEFORDECLARECONSTRUCTION = 59;
  public int JJTFUNCTIONDECL = 60;
  public int JJTDEFINEFUNCTION = 61;
  public int JJTQNAMELPAR = 62;
  public int JJTAS = 63;
  public int JJTPARAMLIST = 64;
  public int JJTPARAM = 65;
  public int JJTENCLOSEDEXPR = 66;
  public int JJTLBRACE = 67;
  public int JJTLBRACEEXPRENCLOSURE = 68;
  public int JJTRBRACE = 69;
  public int JJTQUERYBODY = 70;
  public int JJTEXPR = 71;
  public int JJTVOID = 72;
  public int JJTFLWOREXPR = 73;
  public int JJTIN = 74;
  public int JJTPOSITIONALVAR = 75;
  public int JJTATWORD = 76;
  public int JJTLETCLAUSE = 77;
  public int JJTLETVARIABLE = 78;
  public int JJTWHERECLAUSE = 79;
  public int JJTWHERE = 80;
  public int JJTORDERBYCLAUSE = 81;
  public int JJTORDERBY = 82;
  public int JJTORDERBYSTABLE = 83;
  public int JJTORDERSPECLIST = 84;
  public int JJTORDERSPEC = 85;
  public int JJTORDERMODIFIER = 86;
  public int JJTASCENDING = 87;
  public int JJTDESCENDING = 88;
  public int JJTCOLLATION = 89;
  public int JJTQUANTIFIEDEXPR = 90;
  public int JJTSOME = 91;
  public int JJTEVERY = 92;
  public int JJTSATISFIES = 93;
  public int JJTTYPESWITCHEXPR = 94;
  public int JJTDEFAULT = 95;
  public int JJTCASECLAUSE = 96;
  public int JJTCASE = 97;
  public int JJTIFEXPR = 98;
  public int JJTOREXPR = 99;
  public int JJTANDEXPR = 100;
  public int JJTCOMPARISONEXPR = 101;
  public int JJTRANGEEXPR = 102;
  public int JJTADDITIVEEXPR = 103;
  public int JJTMULTIPLICATIVEEXPR = 104;
  public int JJTUNIONEXPR = 105;
  public int JJTINTERSECTEXCEPTEXPR = 106;
  public int JJTINSTANCEOFEXPR = 107;
  public int JJTTREATEXPR = 108;
  public int JJTCASTABLEEXPR = 109;
  public int JJTCASTEXPR = 110;
  public int JJTCASTAS = 111;
  public int JJTUNARYEXPR = 112;
  public int JJTUNARYMINUS = 113;
  public int JJTUNARYPLUS = 114;
  public int JJTVALIDATEEXPR = 115;
  public int JJTVALIDATELBRACE = 116;
  public int JJTVALIDATESCHEMAMODE = 117;
  public int JJTPATHEXPR = 118;
  public int JJTROOT = 119;
  public int JJTROOTDESCENDANTS = 120;
  public int JJTSLASHSLASH = 121;
  public int JJTSTEPEXPR = 122;
  public int JJTAXISCHILD = 123;
  public int JJTAXISDESCENDANT = 124;
  public int JJTAXISATTRIBUTE = 125;
  public int JJTAXISSELF = 126;
  public int JJTAXISDESCENDANTORSELF = 127;
  public int JJTAXISFOLLOWINGSIBLING = 128;
  public int JJTAXISFOLLOWING = 129;
  public int JJTAT = 130;
  public int JJTAXISPARENT = 131;
  public int JJTAXISANCESTOR = 132;
  public int JJTAXISPRECEDINGSIBLING = 133;
  public int JJTAXISPRECEDING = 134;
  public int JJTAXISANCESTORORSELF = 135;
  public int JJTDOTDOT = 136;
  public int JJTNODETEST = 137;
  public int JJTNAMETEST = 138;
  public int JJTQNAME = 139;
  public int JJTSTAR = 140;
  public int JJTNCNAMECOLONSTAR = 141;
  public int JJTSTARCOLONNCNAME = 142;
  public int JJTPREDICATELIST = 143;
  public int JJTPREDICATE = 144;
  public int JJTINTEGERLITERAL = 145;
  public int JJTDECIMALLITERAL = 146;
  public int JJTDOUBLELITERAL = 147;
  public int JJTDOT = 148;
  public int JJTORDEREDOPEN = 149;
  public int JJTUNORDEREDOPEN = 150;
  public int JJTFUNCTIONCALL = 151;
  public int JJTCONSTRUCTOR = 152;
  public int JJTDIRECTCONSTRUCTOR = 153;
  public int JJTDIRELEMCONSTRUCTOR = 154;
  public int JJTSTARTTAGOPENROOT = 155;
  public int JJTSTARTTAGOPEN = 156;
  public int JJTTAGQNAME = 157;
  public int JJTEMPTYTAGCLOSE = 158;
  public int JJTSTARTTAGCLOSE = 159;
  public int JJTENDTAGOPEN = 160;
  public int JJTS = 161;
  public int JJTENDTAGCLOSE = 162;
  public int JJTDIRATTRIBUTELIST = 163;
  public int JJTVALUEINDICATOR = 164;
  public int JJTDIRATTRIBUTEVALUE = 165;
  public int JJTOPENQUOT = 166;
  public int JJTESCAPEQUOT = 167;
  public int JJTCLOSEQUOT = 168;
  public int JJTOPENAPOS = 169;
  public int JJTESCAPEAPOS = 170;
  public int JJTCLOSEAPOS = 171;
  public int JJTQUOTATTRVALUECONTENT = 172;
  public int JJTQUOTATTRCONTENTCHAR = 173;
  public int JJTAPOSATTRVALUECONTENT = 174;
  public int JJTAPOSATTRCONTENTCHAR = 175;
  public int JJTDIRELEMCONTENT = 176;
  public int JJTELEMENTCONTENTCHAR = 177;
  public int JJTCOMMONCONTENT = 178;
  public int JJTPREDEFINEDENTITYREF = 179;
  public int JJTCHARREF = 180;
  public int JJTLCURLYBRACEESCAPE = 181;
  public int JJTRCURLYBRACEESCAPE = 182;
  public int JJTDIRCOMMENTCONSTRUCTOR = 183;
  public int JJTXMLCOMMENTSTARTFORELEMENTCONTENT = 184;
  public int JJTXMLCOMMENTSTART = 185;
  public int JJTXMLCOMMENTEND = 186;
  public int JJTDIRCOMMENTCONTENTS = 187;
  public int JJTCOMMENTCONTENTCHAR = 188;
  public int JJTCOMMENTCONTENTCHARDASH = 189;
  public int JJTDIRPICONSTRUCTOR = 190;
  public int JJTPROCESSINGINSTRUCTIONSTARTFORELEMENTCONTENT = 191;
  public int JJTPROCESSINGINSTRUCTIONSTART = 192;
  public int JJTPITARGET = 193;
  public int JJTSFORPI = 194;
  public int JJTPROCESSINGINSTRUCTIONEND = 195;
  public int JJTDIRPICONTENTS = 196;
  public int JJTPICONTENTCHAR = 197;
  public int JJTCDATASECTION = 198;
  public int JJTCDATASECTIONSTARTFORELEMENTCONTENT = 199;
  public int JJTCDATASECTIONSTART = 200;
  public int JJTCDATASECTIONEND = 201;
  public int JJTCDATASECTIONCONTENTS = 202;
  public int JJTCDATASECTIONCHAR = 203;
  public int JJTCOMPUTEDCONSTRUCTOR = 204;
  public int JJTCOMPDOCCONSTRUCTOR = 205;
  public int JJTDOCUMENTLBRACE = 206;
  public int JJTCOMPELEMCONSTRUCTOR = 207;
  public int JJTELEMENTQNAMELBRACE = 208;
  public int JJTELEMENTLBRACE = 209;
  public int JJTCONTENTEXPR = 210;
  public int JJTCOMPATTRCONSTRUCTOR = 211;
  public int JJTATTRIBUTEQNAMELBRACE = 212;
  public int JJTATTRIBUTELBRACE = 213;
  public int JJTCOMPTEXTCONSTRUCTOR = 214;
  public int JJTTEXTLBRACE = 215;
  public int JJTCOMPCOMMENTCONSTRUCTOR = 216;
  public int JJTCOMMENTLBRACE = 217;
  public int JJTCOMPPICONSTRUCTOR = 218;
  public int JJTPINCNAMELBRACE = 219;
  public int JJTPILBRACE = 220;
  public int JJTSINGLETYPE = 221;
  public int JJTOCCURRENCEZEROORONE = 222;
  public int JJTTYPEDECLARATION = 223;
  public int JJTSEQUENCETYPE = 224;
  public int JJTEMPTYTOK = 225;
  public int JJTOCCURRENCEZEROORMORE = 226;
  public int JJTOCCURRENCEONEORMORE = 227;
  public int JJTITEM = 228;
  public int JJTATOMICTYPE = 229;
  public int JJTQNAMEFORATOMICTYPE = 230;
  public int JJTQNAMEFORSEQUENCETYPE = 231;
  public int JJTANYKINDTEST = 232;
  public int JJTNODELPARFORKINDTEST = 233;
  public int JJTDOCUMENTTEST = 234;
  public int JJTDOCUMENTLPAR = 235;
  public int JJTDOCUMENTLPARFORKINDTEST = 236;
  public int JJTTEXTTEST = 237;
  public int JJTTEXTLPARFORKINDTEST = 238;
  public int JJTCOMMENTTEST = 239;
  public int JJTCOMMENTLPARFORKINDTEST = 240;
  public int JJTPITEST = 241;
  public int JJTPROCESSINGINSTRUCTIONLPARFORKINDTEST = 242;
  public int JJTNCNAMEFORPI = 243;
  public int JJTSTRINGLITERALFORKINDTEST = 244;
  public int JJTATTRIBUTETEST = 245;
  public int JJTATTRIBUTETYPE = 246;
  public int JJTATTRIBUTETYPEFORKINDTEST = 247;
  public int JJTCOMMAFORKINDTEST = 248;
  public int JJTATTRIBNAMEORWILDCARD = 249;
  public int JJTANYNAME = 250;
  public int JJTSCHEMAATTRIBUTETEST = 251;
  public int JJTSCHEMAATTRIBUTETYPE = 252;
  public int JJTSCHEMAATTRIBUTETYPEFORKINDTEST = 253;
  public int JJTATTRIBUTEDECLARATION = 254;
  public int JJTELEMENTTEST = 255;
  public int JJTELEMENTTYPE = 256;
  public int JJTELEMENTTYPEFORKINDTEST = 257;
  public int JJTELEMENTTYPEFORDOCUMENTTEST = 258;
  public int JJTNILLABLE = 259;
  public int JJTELEMENTNAMEORWILDCARD = 260;
  public int JJTSCHEMAELEMENTTEST = 261;
  public int JJTSCHEMAELEMENTTYPE = 262;
  public int JJTSCHEMAELEMENTTYPEFORKINDTEST = 263;
  public int JJTSCHEMAELEMENTTYPEFORDOCUMENTTEST = 264;
  public int JJTELEMENTDECLARATION = 265;
  public int JJTATTRIBUTENAME = 266;
  public int JJTQNAMEFORITEMTYPE = 267;
  public int JJTELEMENTNAME = 268;
  public int JJTTYPENAME = 269;


  public String[] jjtNodeName = {
    "XPath2",
    "QueryList",
    "Module",
    "VersionDecl",
    "XQueryVersion",
    "StringLiteralForVersion",
    "XQueryEncoding",
    "MainModule",
    "LibraryModule",
    "ModuleDecl",
    "ModuleNamespace",
    "NCNameForPrefix",
    "AssignEquals",
    "URLLiteral",
    "Prolog",
    "Setter",
    "Import",
    "Separator",
    "NamespaceDecl",
    "DeclareNamespace",
    "XMLSpaceDecl",
    "DeclareXMLSpace",
    "XMLSpacePreserve",
    "XMLSpaceStrip",
    "DefaultNamespaceDecl",
    "DeclareDefaultElement",
    "DeclareDefaultFunction",
    "Namespace",
    "OrderingModeDecl",
    "DeclareOrdering",
    "Ordered",
    "Unordered",
    "EmptyOrderingDecl",
    "DeclareDefaultOrderingEmpty",
    "EmptyGreatest",
    "EmptyLeast",
    "InheritNamespacesDecl",
    "DeclareInheritNamespaces",
    "Yes",
    "No",
    "DefaultCollationDecl",
    "DeclareCollation",
    "BaseURIDecl",
    "DeclareBaseURI",
    "SchemaImport",
    "ImportSchemaToken",
    "AtStringLiteral",
    "StringLiteral",
    "SchemaPrefix",
    "DefaultElement",
    "ModuleImport",
    "ImportModuleToken",
    "VarDecl",
    "DefineVariable",
    "VarName",
    "ColonEquals",
    "External",
    "ConstructionDecl",
    "DeclareConstruction",
    "SchemaModeForDeclareConstruction",
    "FunctionDecl",
    "DefineFunction",
    "QNameLpar",
    "As",
    "ParamList",
    "Param",
    "EnclosedExpr",
    "Lbrace",
    "LbraceExprEnclosure",
    "Rbrace",
    "QueryBody",
    "Expr",
    "void",
    "FLWORExpr",
    "In",
    "PositionalVar",
    "AtWord",
    "LetClause",
    "LetVariable",
    "WhereClause",
    "Where",
    "OrderByClause",
    "OrderBy",
    "OrderByStable",
    "OrderSpecList",
    "OrderSpec",
    "OrderModifier",
    "Ascending",
    "Descending",
    "Collation",
    "QuantifiedExpr",
    "Some",
    "Every",
    "Satisfies",
    "TypeswitchExpr",
    "Default",
    "CaseClause",
    "Case",
    "IfExpr",
    "OrExpr",
    "AndExpr",
    "ComparisonExpr",
    "RangeExpr",
    "AdditiveExpr",
    "MultiplicativeExpr",
    "UnionExpr",
    "IntersectExceptExpr",
    "InstanceofExpr",
    "TreatExpr",
    "CastableExpr",
    "CastExpr",
    "CastAs",
    "UnaryExpr",
    "UnaryMinus",
    "UnaryPlus",
    "ValidateExpr",
    "ValidateLbrace",
    "ValidateSchemaMode",
    "PathExpr",
    "Root",
    "RootDescendants",
    "SlashSlash",
    "StepExpr",
    "AxisChild",
    "AxisDescendant",
    "AxisAttribute",
    "AxisSelf",
    "AxisDescendantOrSelf",
    "AxisFollowingSibling",
    "AxisFollowing",
    "At",
    "AxisParent",
    "AxisAncestor",
    "AxisPrecedingSibling",
    "AxisPreceding",
    "AxisAncestorOrSelf",
    "DotDot",
    "NodeTest",
    "NameTest",
    "QName",
    "Star",
    "NCNameColonStar",
    "StarColonNCName",
    "PredicateList",
    "Predicate",
    "IntegerLiteral",
    "DecimalLiteral",
    "DoubleLiteral",
    "Dot",
    "OrderedOpen",
    "UnorderedOpen",
    "FunctionCall",
    "Constructor",
    "DirectConstructor",
    "DirElemConstructor",
    "StartTagOpenRoot",
    "StartTagOpen",
    "TagQName",
    "EmptyTagClose",
    "StartTagClose",
    "EndTagOpen",
    "S",
    "EndTagClose",
    "DirAttributeList",
    "ValueIndicator",
    "DirAttributeValue",
    "OpenQuot",
    "EscapeQuot",
    "CloseQuot",
    "OpenApos",
    "EscapeApos",
    "CloseApos",
    "QuotAttrValueContent",
    "QuotAttrContentChar",
    "AposAttrValueContent",
    "AposAttrContentChar",
    "DirElemContent",
    "ElementContentChar",
    "CommonContent",
    "PredefinedEntityRef",
    "CharRef",
    "LCurlyBraceEscape",
    "RCurlyBraceEscape",
    "DirCommentConstructor",
    "XmlCommentStartForElementContent",
    "XmlCommentStart",
    "XmlCommentEnd",
    "DirCommentContents",
    "CommentContentChar",
    "CommentContentCharDash",
    "DirPIConstructor",
    "ProcessingInstructionStartForElementContent",
    "ProcessingInstructionStart",
    "PITarget",
    "SForPI",
    "ProcessingInstructionEnd",
    "DirPIContents",
    "PIContentChar",
    "CDataSection",
    "CdataSectionStartForElementContent",
    "CdataSectionStart",
    "CdataSectionEnd",
    "CDataSectionContents",
    "CDataSectionChar",
    "ComputedConstructor",
    "CompDocConstructor",
    "DocumentLbrace",
    "CompElemConstructor",
    "ElementQNameLbrace",
    "ElementLbrace",
    "ContentExpr",
    "CompAttrConstructor",
    "AttributeQNameLbrace",
    "AttributeLbrace",
    "CompTextConstructor",
    "TextLbrace",
    "CompCommentConstructor",
    "CommentLbrace",
    "CompPIConstructor",
    "PINCNameLbrace",
    "PILbrace",
    "SingleType",
    "OccurrenceZeroOrOne",
    "TypeDeclaration",
    "SequenceType",
    "EmptyTok",
    "OccurrenceZeroOrMore",
    "OccurrenceOneOrMore",
    "Item",
    "AtomicType",
    "QNameForAtomicType",
    "QNameForSequenceType",
    "AnyKindTest",
    "NodeLparForKindTest",
    "DocumentTest",
    "DocumentLpar",
    "DocumentLparForKindTest",
    "TextTest",
    "TextLparForKindTest",
    "CommentTest",
    "CommentLparForKindTest",
    "PITest",
    "ProcessingInstructionLparForKindTest",
    "NCNameForPI",
    "StringLiteralForKindTest",
    "AttributeTest",
    "AttributeType",
    "AttributeTypeForKindTest",
    "CommaForKindTest",
    "AttribNameOrWildcard",
    "AnyName",
    "SchemaAttributeTest",
    "SchemaAttributeType",
    "SchemaAttributeTypeForKindTest",
    "AttributeDeclaration",
    "ElementTest",
    "ElementType",
    "ElementTypeForKindTest",
    "ElementTypeForDocumentTest",
    "Nillable",
    "ElementNameOrWildcard",
    "SchemaElementTest",
    "SchemaElementType",
    "SchemaElementTypeForKindTest",
    "SchemaElementTypeForDocumentTest",
    "ElementDeclaration",
    "AttributeName",
    "QNameForItemType",
    "ElementName",
    "TypeName",
  };
}
