/* Generated By:JJTree: Do not edit this line. /home/jukka/src/jackrabbit/jackrabbit-spi-commons/target/generated-sources/jjtree/org/apache/jackrabbit/spi/commons/query/sql/JCRSQLParserVisitor.java */

package org.apache.jackrabbit.spi.commons.query.sql;

public interface JCRSQLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTQuery node, Object data);
  public Object visit(ASTSelectList node, Object data);
  public Object visit(ASTFromClause node, Object data);
  public Object visit(ASTWhereClause node, Object data);
  public Object visit(ASTPredicate node, Object data);
  public Object visit(ASTLowerFunction node, Object data);
  public Object visit(ASTUpperFunction node, Object data);
  public Object visit(ASTOrExpression node, Object data);
  public Object visit(ASTAndExpression node, Object data);
  public Object visit(ASTNotExpression node, Object data);
  public Object visit(ASTBracketExpression node, Object data);
  public Object visit(ASTContainsExpression node, Object data);
  public Object visit(ASTLiteral node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTExcerptFunction node, Object data);
  public Object visit(ASTOrderByClause node, Object data);
  public Object visit(ASTOrderSpec node, Object data);
  public Object visit(ASTAscendingOrderSpec node, Object data);
  public Object visit(ASTDescendingOrderSpec node, Object data);
}
