/* Generated By:JJTree: Do not edit this line. /home/jukka/src/jackrabbit/jackrabbit-spi-commons/target/generated-sources/jjtree/org/apache/jackrabbit/spi/commons/query/xpath/XPathVisitor.java */

package org.apache.jackrabbit.spi.commons.query.xpath;

public interface XPathVisitor
{
  public Object visit(SimpleNode node, Object data);
}
