/* Generated By:JJTree: Do not edit this line. JCRQLParserVisitor.java */
/*
 * Copyright 2004 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.jackrabbit.core.search.jcrql;

public interface JCRQLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTSelectClause node, Object data);
  public Object visit(ASTFromClause node, Object data);
  public Object visit(ASTNodeType node, Object data);
  public Object visit(ASTLocationClause node, Object data);
  public Object visit(ASTWhereClause node, Object data);
  public Object visit(ASTOrExpr node, Object data);
  public Object visit(ASTAndExpr node, Object data);
  public Object visit(ASTNotExpr node, Object data);
  public Object visit(ASTRelExpr node, Object data);
  public Object visit(ASTBracketExpr node, Object data);
  public Object visit(ASTValue node, Object data);
  public Object visit(ASTTextsearchClause node, Object data);
  public Object visit(ASTOrderClause node, Object data);
}
