/* Generated By:JJTree&JavaCC: Do not edit this line. JCRQLParserConstants.java */
/*
 * Copyright 2004 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.jackrabbit.core.search.jcrql;

public interface JCRQLParserConstants {

  int EOF = 0;
  int SELECT = 4;
  int FROM = 5;
  int LOCATION = 6;
  int WHERE = 7;
  int TEXTSEARCH = 8;
  int ORDER = 9;
  int BY = 10;
  int SCORE = 11;
  int ASCENDING = 12;
  int DESCENDING = 13;
  int LIKE = 14;
  int AND = 15;
  int OR = 16;
  int NOT = 17;
  int STRING_LITERAL = 18;
  int DIGIT = 19;
  int TRUE = 20;
  int FALSE = 21;
  int UUID = 22;
  int TIME_LOW = 23;
  int TIME_MID = 24;
  int TIME_HIGH_AND_VERSION = 25;
  int CLOCK_SEQ = 26;
  int NODE = 27;
  int HEX_OCTET = 28;
  int HEX_DIGIT = 29;
  int ISO_DATE = 30;
  int YEAR = 31;
  int MONTH = 32;
  int DAY = 33;
  int HOUR = 34;
  int MINUTE = 35;
  int SEC = 36;
  int SEC_FRAC = 37;
  int DOUBLE = 38;
  int EXP_PART = 39;
  int TYPE_SUFFIX = 40;
  int ULONG = 41;
  int LONG = 42;
  int EQ = 43;
  int GT = 44;
  int LT = 45;
  int LE = 46;
  int GE = 47;
  int NE = 48;
  int NCName = 49;
  int NCNameChar = 50;
  int Letter = 51;
  int BaseChar = 52;
  int Ideographic = 53;
  int CombiningChar = 54;
  int Digit = 55;
  int Extender = 56;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\n\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"LOCATION\"",
    "\"WHERE\"",
    "\"TEXTSEARCH\"",
    "\"ORDER\"",
    "\"BY\"",
    "\"SCORE\"",
    "\"ASCENDING\"",
    "\"DESCENDING\"",
    "\"LIKE\"",
    "\"AND\"",
    "\"OR\"",
    "\"NOT\"",
    "<STRING_LITERAL>",
    "<DIGIT>",
    "\"true\"",
    "\"false\"",
    "<UUID>",
    "<TIME_LOW>",
    "<TIME_MID>",
    "<TIME_HIGH_AND_VERSION>",
    "<CLOCK_SEQ>",
    "<NODE>",
    "<HEX_OCTET>",
    "<HEX_DIGIT>",
    "<ISO_DATE>",
    "<YEAR>",
    "<MONTH>",
    "<DAY>",
    "<HOUR>",
    "<MINUTE>",
    "<SEC>",
    "<SEC_FRAC>",
    "<DOUBLE>",
    "<EXP_PART>",
    "<TYPE_SUFFIX>",
    "<ULONG>",
    "<LONG>",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"<>\"",
    "<NCName>",
    "<NCNameChar>",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<Digit>",
    "<Extender>",
    "\"*\"",
    "\",\"",
    "\":\"",
    "\"/*\"",
    "\"//\"",
    "\"/\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
  };

}
