/* Generated By:JJTree: Do not edit this line. JCRQLParserTreeConstants.java */
/*
 * Copyright 2004 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.apache.jackrabbit.core.search.jcrql;

public interface JCRQLParserTreeConstants
{
  public int JJTSTATEMENT = 0;
  public int JJTSELECTCLAUSE = 1;
  public int JJTVOID = 2;
  public int JJTFROMCLAUSE = 3;
  public int JJTNODETYPE = 4;
  public int JJTLOCATIONCLAUSE = 5;
  public int JJTWHERECLAUSE = 6;
  public int JJTOREXPR = 7;
  public int JJTANDEXPR = 8;
  public int JJTNOTEXPR = 9;
  public int JJTRELEXPR = 10;
  public int JJTBRACKETEXPR = 11;
  public int JJTVALUE = 12;
  public int JJTTEXTSEARCHCLAUSE = 13;
  public int JJTORDERCLAUSE = 14;


  public String[] jjtNodeName = {
    "Statement",
    "SelectClause",
    "void",
    "FromClause",
    "NodeType",
    "LocationClause",
    "WhereClause",
    "OrExpr",
    "AndExpr",
    "NotExpr",
    "RelExpr",
    "BracketExpr",
    "Value",
    "TextsearchClause",
    "OrderClause",
  };
}
